language: python
python:
#  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
#  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
#  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f requirements/test-environment.yaml python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
#  - pip install -r requirements/pip-requirements.txt
#  - conda install -c conda-forge iris
  - pip install .
# command to run tests
script: pytest
