name: test-environment
channels:
  - conda-forge
dependencies:
  - python=$TRAVIS_PYTHON_VERSION
  - pyYAML>=5.1
  - numpy>=1.16.1
  - netCDF4>=1.5
  - iris>=2.2.0
  - pip
  - pip:
    - scriptengine>=0.5
